/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.55
 * Generated at: 2020-06-23 01:18:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>쇼부</title>\n");
      out.write("    <script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/main.js\"></script>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/main.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    <div class=\"area\"></div>\n");
      out.write("    <nav class=\"main-menu\">\n");
      out.write("        <ul>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"http://justinfarrow.com\">\n");
      out.write("                    <i class=\"fa fa-home fa-2x\"></i>\n");
      out.write("                    <span class=\"nav-text\">\n");
      out.write("                        Home\n");
      out.write("                    </span>\n");
      out.write("                </a>\n");
      out.write("\n");
      out.write("            </li>\n");
      out.write("            <li class=\"has-subnav\">\n");
      out.write("                <a href=\"#\">₩\n");
      out.write("                    <i class=\"fa fa-play fa-2x\"></i>\n");
      out.write("                    <span class=\"nav-text\">\n");
      out.write("                        Game\n");
      out.write("                    </span>\n");
      out.write("                </a>\n");
      out.write("\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">\n");
      out.write("                    <i class=\"fa fa-bar-chart-o fa-2x\"></i>\n");
      out.write("                    <span class=\"nav-text\">\n");
      out.write("                        Statistics\n");
      out.write("                    </span>\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">\n");
      out.write("                    <i class=\"fa fa-map-marker fa-2x\"></i>\n");
      out.write("                    <span class=\"nav-text\">\n");
      out.write("                        Maps\n");
      out.write("                    </span>\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("\n");
      out.write("        <ul class=\"logout\">\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#\">\n");
      out.write("                    <i class=\"fa fa-power-off fa-2x\"></i>\n");
      out.write("                    <span class=\"nav-text\">\n");
      out.write("                        Logout\n");
      out.write("                    </span>\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("    </nav>\n");
      out.write("    <div class=\"search-wrapper\">\n");
      out.write("        <div class=\"input-holder\">\n");
      out.write("            <input type=\"text\" class=\"search-input\" placeholder=\"Type to search\" />\n");
      out.write("            <button class=\"search-icon\" onclick=\"searchToggle(this, event);\"><span></span></button>\n");
      out.write("        </div>\n");
      out.write("        <span class=\"close\" onclick=\"searchToggle(this, event);\"></span>\n");
      out.write("    </div>\n");
      out.write("    <table>\n");
      out.write("        <tr>\n");
      out.write("            <td>\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <p>Architect & Engineer</p>\n");
      out.write("                </div>\n");
      out.write("            </td>\n");
      out.write("            <td>\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <p>Architect & Engineer</p>\n");
      out.write("                </div>\n");
      out.write("            </td>\n");
      out.write("            <td>\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <p>Architect & Engineer</p>\n");
      out.write("                </div>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td>\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <p>Architect & Engineer</p>\n");
      out.write("                </div>\n");
      out.write("            </td>\n");
      out.write("            <td>\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <p>Architect & Engineer</p>\n");
      out.write("                </div>\n");
      out.write("            </td>\n");
      out.write("            <td>\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <p>Architect & Engineer</p>\n");
      out.write("                </div>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td>\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <p>Architect & Engineer</p>\n");
      out.write("                </div>\n");
      out.write("            </td>\n");
      out.write("            <td>\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <p>Architect & Engineer</p>\n");
      out.write("                </div>\n");
      out.write("            </td>\n");
      out.write("            <td>\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <p>Architect & Engineer</p>\n");
      out.write("                </div>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("    <div id=\"chat-circle\" class=\"btn btn-raised\">\n");
      out.write("            <div id=\"chat-overlay\"></div>\n");
      out.write("                <i class=\"fa fa-comments fa-2x chatIcon\"></i>\n");
      out.write("        </div>\n");
      out.write("      \n");
      out.write("      <div class=\"chat-box\">\n");
      out.write("        <div class=\"chat-box-header\">\n");
      out.write("          ChatBot\n");
      out.write("          <span class=\"chat-box-toggle\"><i class=\"fa fa-times\"></i></span>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"chat-box-body\">\n");
      out.write("          <div class=\"chat-box-overlay\">   \n");
      out.write("          </div>\n");
      out.write("          <div class=\"chat-logs\">\n");
      out.write("           \n");
      out.write("          </div><!--chat-log -->\n");
      out.write("        </div>\n");
      out.write("        <div class=\"chat-input\">      \n");
      out.write("          <form>\n");
      out.write("            <input type=\"text\" id=\"chat-input\" placeholder=\"Send a message...\"/>\n");
      out.write("          <button type=\"submit\" class=\"chat-submit\" id=\"chat-submit\"><i class=\"material-icons\">send</i></button>\n");
      out.write("          </form>      \n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("   \n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
